version: 2
sources:
    - name: raw
      schema: gz_raw_data
      description: raw data from lewagon
      tables:
        - name: sales
          identifier: raw_gz_sales
          description: sales info of products
          tests:
            - unique:
                column_name: "(pdt_id || '-' || orders_id )"
          freshness: 
            warn_after: 
              count: 90
              period: day
          loaded_at_field: CAST(date_date AS timestamp)
        - name: product
          identifier: raw_gz_product
          description: all products
          tests:
            - unique:
                column_name: products_id
        - name: ship
          identifier: raw_gz_ship
          description: shipping info of products
          tests:
            - unique:
                column_name: orders_id


