version: 2
sources:
    - name: raw
      schema: gz_raw_data
      description: raw data from lewagon
      tables:
        - name: sales
          identifier: raw_gz_sales
          description: sales info of products
          tests:
            - unique:
                column_name: "(pdt_id || '-' || orders_id )"
          freshness: 
            warn_after: 
              count: 90
              period: day
          loaded_at_field: CAST(date_date AS timestamp)
        - name: product
          identifier: raw_gz_product
          description: all products
          tests:
            - unique:
                column_name: products_id
        - name: ship
          identifier: raw_gz_ship
          description: shipping info of products
          tests:
            - unique:
                column_name: orders_id
        - name: adwords
          identifier: raw_gz_adwords
          tests:
            - unique:
               column_name: "(date_date || '-' || campaign_key)"
        - name: bing
          identifier: raw_gz_bing
          tests:
            - unique:
               column_name: "(date_date || '-' || campaign_key)"
        - name: criteo
          identifier: raw_gz_criteo
          tests:
            - unique:
               column_name: "(date_date || '-' || campaign_key)"
        - name: facebook
          identifier: raw_gz_facebook
          tests:
            - unique:
               column_name: "(date_date || '-' || campaign_key)"

models:
  - name: int_campaigns_day
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name: date_date  


